name: CI/CD - Build e Deploy para AWS K3s

on:
  push:
    branches:
      - master   # roda sempre que fizer push na branch master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¦ Checkout do cÃ³digo
        uses: actions/checkout@v3

      - name: âš™ï¸ Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: ğŸ§° Instalar dependÃªncias e gerar build Angular
        working-directory: ./client  # diretÃ³rio do seu projeto Angular
        run: |
          npm install --legacy-peer-deps
          npm run build --prod

      - name: ğŸ³ Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: ğŸ—ï¸ Build e Push da imagem Docker
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ecommercemilly:latest ./client
          docker push ${{ secrets.DOCKER_USERNAME }}/ecommercemilly:latest

      - name: â˜ï¸ Deploy no K3s (EC2)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            echo "Atualizando deployment do frontend no K3s..."
            kubectl rollout restart deployment frontend -n app-demo
            kubectl get pods -n app-demo

