name: Deploy Angular to AWS K3s

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js (Angular)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3️⃣ Instalar dependências
      - name: Install dependencies
        run: npm install --legacy-peer-deps
        working-directory: ./client

      # 4️⃣ Build Angular app
      - name: Build Angular app
        run: npm run build -- --configuration production
        working-directory: ./client

      # 5️⃣ Login no Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 6️⃣ Build e Push da imagem Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./client
          push: true
          tags: gillrosas22/ecommercemilly:latest

      # 7️⃣ Atualizar frontend no K3s
      - name: Update K3s Deployment
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.AWS_EC2_IP }}
          username: ubuntu
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          script: |
            echo "Atualizando frontend no K3s..."
            sudo kubectl rollout restart deployment frontend -n app-demo
            sudo kubectl rollout status deployment frontend -n app-demo
            echo "✅ Atualização concluída!"
