name: Docker CI + K3s Deploy

on:
  push:
    branches:
      - master

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout do código
      - uses: actions/checkout@v3

      # 2️⃣ Login no Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3️⃣ Build da imagem Docker
      - name: Build Docker image
        run: docker build -t gillrosas22/ecommercemilly:v3 ./client

      # 4️⃣ Push da imagem
      - name: Push Docker image
        run: docker push gillrosas22/ecommercemilly:v3

      # 5️⃣ Deploy no K3s via SSH com sudo
      - name: Update K3s Deployment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.K3S_HOST }}
          username: ${{ secrets.K3S_USER }}
          key: ${{ secrets.K3S_SSH_KEY }}
          script: |
            export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
            echo "Atualizando deployment do frontend no K3s..."
            sudo kubectl set image deployment/frontend frontend=gillrosas22/ecommercemilly:v3 -n app-demo
            sudo kubectl set image deployment/backend backend=gillrosas22/ecommercemilly:v3 -n app-demo
            sudo kubectl rollout status deployment/frontend -n app-demo
            sudo kubectl rollout status deployment/backend -n app-demo
            kubectl get pods -n app-demo
